server:
  port: ${PORT:8080}

spring:
  application:
    name: webflux-contacts-hex
  r2dbc:
    url: r2dbc:h2:file:///.//contactsdb;DB_CLOSE_ON_EXIT=TRUE;AUTO_RECONNECT=TRUE
  sql:
    init:
      mode: always
      schema-locations: classpath:init_db.sql

management:
  endpoints:
    web:
      exposure:
        include: health,info
