server:
  port: ${PORT:8080}

spring:
  application:
    name: webflux-contacts-hex
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/contacts}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
